from django.db import models
from django.utils import timezone

class Syslog(models.Model):
    type = models.CharField(max_length=50, default="")  # Log type/heading (i.e Appointment Created, EMR viewing)
    message = models.CharField(max_length=200, default="")  # Log message, usually generated by the system
    date_created = models.DateTimeField(default=timezone.now)

    @staticmethod
    def log(_type, _message):
        Syslog.objects.create(type=_type, message = _message, date_created = timezone.now())

    @staticmethod
    def logUser(_type, _message, _user):
        _message += ":{0}, {1}".format(_user.lastName, _user.firstName)
        Syslog.log(_type, _message)

