# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-29 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='UserName',
            new_name='userName',
        ),
    ]
