from django.shortcuts import render, get_object_or_404, render_to_response
from django.core.urlresolvers import reverse

from django.contrib.messages import error
from django.views.generic.edit import CreateView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.core.context_processors import csrf
from User.models import *
from .forms import PatientForm
from django.template import loader
from django.contrib import messages
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from User.models import *
from django.core.urlresolvers import reverse
from django.views.generic import View


#todo see if needed

# from User.models import *
# from .forms import PatientForm

# Create your views here.

@csrf_protect #add security
def register(request):
    form = RegistrationForm(request.POST)
    if form.is_valid():
        user = User.objects.create_user(
            username=form.cleaned_data['username'],  # cleaned_data is autogenerated data. can be modified in form
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name']
        )

        p = Patient.objects.create(user=user)
        p.save()
        login(request, user)
        request.session['user_model'] = p

        return HttpResponseRedirect(reverse('User:dashboard'), args=(p.id,))
    else:
        form = RegistrationForm()
        variables = RequestContext(request, {'form': form})
        return render_to_response('registration/register.html', variables)

class LoginView(View):

    def post(self, request):
        lform = LoginForm(request.POST)

        if(lform.is_valid()):
            user = authenticate(username=lform.cleaned_data['username'], password=lform.cleaned_data['password'])
            if user is not None:
                login(request, user)
                if hasattr(user, 'patient'):
                    request.session['user_type'] = 'patient'
                elif hasattr(user, 'nurse'):
                    request.session['user_type'] = 'nurse'
                elif hasattr(user, 'doctor'):
                    request.session['user_type'] = 'doctor'

                uid = getattr(user, request.session['user_type']).id

                return HttpResponseRedirect(reverse('User:dashboard'))

        return HttpResponseRedirect(reverse('login'))

    def get(self, request):
        form = LoginForm()

        return render(request, 'logIn/index.html', {'form': form})



def register_success(request):
    return render_to_response('registration/success.html')

def logout_page(request):
    logout(request)


"""this method will process a user's request to log in"""
def logIn(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username = username, password = password)
    if user is not None:
        if user.is_active:
            login(request, user)

            return HttpResponseRedirect(reverse('User : dashboard', args=(request.user.id),))
        else:
            return messages.error(request, 'Your account has been disabled. Contact your administrator.')
    else:
        return messages.error(request, 'Invalid login.')

@login_required
def home(request):
    return render_to_response('home.html',{'user': request.user })

# def index(request):
#
#     return render(request, 'logIn/index.html')


# def authenticate(request):
#     response = 'neutral'
#     #queryset
#     patientquery = Patient.objects.filter(UserName=request.POST['UN'])
#
#     if patientquery.exists():
#         response = 'well the username exists'
#         passfromdb = patientquery.values('Password')[0]['Password']
#         if passfromdb == request.POST['PW']:
#             response = response +' hell yeah you in'
#         else:
#             response = response+ ' gettt outta here with that password tho'
#     else:
#         response = 'username does not exist'
#     return HttpResponse(response )


#todo see if you can add other params to a generic user paramater
# class Register(CreateView):
#     model = Patient
#     template_name = 'login/register_form.html'
#     form_class = PatientForm

